name: Content request (chapter or timeline)
description: Propose a new chapter (MDX) or timeline entry (YAML)
labels: ["content"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - chapter
        - timeline
    validations:
      required: true

  - type: input
    id: proposed_title
    attributes:
      label: Proposed title
      placeholder: e.g., Oslo Accords (1993–1995)
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope & significance
      placeholder: Why this matters and what it covers (2–4 sentences).

  - type: textarea
    id: sources
    attributes:
      label: Sources (CSL-JSON ids or URLs)
      placeholder: |
        - sayigh1997
        - https://www.icj-cij.org/case/131
    validations:
      required: true

  - type: textarea
    id: places
    attributes:
      label: Places (match gazetteer ids/names)
      placeholder: '["Gaza","Jaffa","Hebron"]'

  - typ
